[package]
name = "copperon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.13.0"

[profile.test]
opt-level=3

[profile.dev]
opt-level=3